name: 'Run gradle publish'
description: 'Publish the current build to GitHub Packages'

inputs:
  access-token:
    description: 'Service account access token that allows publishing packages'
    required: true
  package-version:
    description: 'Package Version'
    required: true
  username:
    description: 'Service account username that allows publishing packages'
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish package
      id: maven-publish
      run: |
        echo "Package Version = ${INPUT_PACKAGE_VERSION}"
        
        ./gradlew \
          publish \
          -PpackageVersion=$INPUT_PACKAGE_VERSION
      shell: bash
      env:
        CI: true
        INPUT_PACKAGE_VERSION: ${{ inputs.package-version }}
        TOKEN: ${{ inputs.access-token }}
        USERNAME: ${{ inputs.username }}
