name: 'Run sonar analysis'
description: 'Run sonar analysis on a PR or branch'

runs:
  using: "composite"
  steps:
    - name: Run Sonarqube PR Analysis
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        ./gradlew sonar \
          -Dsonar.pullrequest.base=develop \
          -Dsonar.pullrequest.branch=${{ github.head_ref || github.ref_name }} \
          -Dsonar.pullrequest.key=${{ github.event.number }}
      shell: bash
      env:
        CI: true

    - name: Run Sonarqube Branch Analysis
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        ./gradlew sonar \
          -Dsonar.branch.name=${{ github.head_ref || github.ref_name }}
      shell: bash
      env:
        CI: true
