name: 'Generate version code'
description: 'Generates a version code based off the current Unix epoch'

outputs:
  version-code:
    description: 'Version code'
    value: ${{ steps.generate-version-code.outputs.version-code }}

runs:
  using: "composite"
  steps:
    - name: Generate version code
      id: generate-version-code
      run: |
        VERSION_CODE=$(date +%s)
        echo "VERSION_CODE = $VERSION_CODE"
        echo "version-code=$VERSION_CODE" >> $GITHUB_OUTPUT
      shell: bash
