name: 'Run gradle assemble and bundle (release build type)'
description: 'Run the "assembleRelease" and "bundleRelease" commands for a Gradle project'

inputs:
  version-name:
    description: 'Version name'
    required: true

outputs:
  aab-paths:
    description: 'Paths to build flavor aab'
    value: ${{ steps.gradle-assemble-and-bundle.outputs.aab-paths }}

runs:
  using: "composite"
  steps:
    - name: Bundle release
      id: gradle-assemble-and-bundle
      run: |
        echo "Version name = ${INPUT_VERSION_NAME}"
        
        ./gradlew \
          assembleRelease \
          -PversionName=$INPUT_VERSION_NAME
      shell: bash
      env:
        CI: true
        INPUT_VERSION_NAME: ${{ inputs.version-name }}
