name: 'Run gradle check'
description: 'Run the "check" command for a Gradle project'

inputs:
  architecture:
    description: 'AVD architecture to use'
    required: false
    default: 'x86_64'
  device-profile:
    description: 'AVD device profile to use'
    required: false
    default: 'pixel_5'
  locale:
    description: 'Locale used within the emulator'
    required: false
    default: 'en-GB'

runs:
  using: "composite"
  steps:
    - name: Run gradle connected test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: ${{ inputs.architecture }}
        avd-name: ${{ inputs.device-profile }}
        disable-animations: true
        disable-linux-hw-accel: false
        force-avd-creation: true
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -change-locale ${{ inputs.locale }}
        profile: ${{ inputs.device-profile }}
        # connectedDebugAndroidTest fails intermittently in the pipeline as no tests are found for :theme
        script: |
          ./gradlew connectedDebugAndroidTest --continue --stacktrace
