name: 'Version name'
description: 'Combines the inputs into a version name'

inputs:
  version-code:
    description: 'Version code'
    required: true
  version-name:
    description: 'Version name'
    required: true

outputs:
  version-name:
    description: 'Version name'
    value: ${{ steps.version-name.outputs.version-name }}

runs:
  using: "composite"
  steps:
    - name: Generate version name
      id: version-name
      shell: bash
      run: |
        version=$(git-conventional-commits version)
        
        echo "new version name: $version"
        echo "version-name=$version" >> $GITHUB_OUTPUT
      env:
        INPUT_VERSION_CODE: ${{ inputs.version-code }}
        INPUT_VERSION_NAME: ${{ inputs.version-name }}
