name: 'Get the latest annotated tag'
description: 'Gets the latest tag on a branch'

inputs:
  version-name:
    description: 'Version name'
    required: true

outputs:
  current-tag:
    description: 'Current tag'
    value: ${{ steps.get-latest-tag.outputs.current-tag }}

runs:
  using: "composite"
  steps:
    - name: Git tag bundles
      run: |
        echo "Tagging with $INPUT_VERSION_NAME"
        
        git tag -a "v$INPUT_VERSION_NAME" -m "Publishing v$INPUT_VERSION_NAME"
        git push origin "v$INPUT_VERSION_NAME"
      shell: bash
      env:
        INPUT_VERSION_NAME: ${{ inputs.version-name }}
