name: 'Upload dokka'
description: 'Zip and upload dokka-produced documentation'

runs:
  using: "composite"
  steps:
    - name: Bundle Dokka documentation
      id: zipDokka
      run: |
        zip -9 -r documentation.zip ./build/dokka
      shell: bash

    - name: Upload Dokka Documentation
      id: uploadDokka
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: documentation
        retention-days: 14
        path: |-
          documentation.zip
