name: 'Upload dokka'
description: 'Zip and upload dokka-produced documentation'

runs:
  using: "composite"
  steps:
    - name: Bundle Dokka documentation
      id: zipDokka
      run: |
        zip -9 -r documentation.zip ./build/dokka
      shell: bash

    - name: Upload Dokka Documentation
      id: uploadDokka
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: documentation
        retention-days: 14
        path: |-
          documentation.zip
