name: 'Upload dokka'
description: 'Zip and upload dokka-produced documentation'

runs:
  using: "composite"
  steps:
    - name: Bundle Dokka documentation
      id: zipDokka
      run: |
        zip -9 -r documentation.zip ./build/dokka
      shell: bash

    - name: Upload Dokka Documentation
      id: uploadDokka
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # pin@v3
      with:
        name: documentation
        retention-days: 14
        path: |
          documentation.zip
