name: On Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPullRequestJob:
    env:
      ANDROID_HOME: ${{ github.workspace }}/bin/androidSdk
    name: Verify code base when pull request is published/updated
    runs-on: ubuntu-24.04
    steps:
      - name: Run pull request workflow
        uses: govuk-one-login/mobile-android-pipelines@52195ad1a564b1c8f9ed52eb83f5aa4dc919193d
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
