name: On Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPullRequestJob:
    env:
      ANDROID_HOME: ${{ github.workspace }}/bin/androidSdk
    name: Verify code base when pull request is published/updated
    runs-on: ubuntu-latest
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    steps:
      - name: Run pull request workflow
        uses: govuk-one-login/mobile-android-pipelines@0ced974a40b06d5a92513639e9c82f7cb2f811cc
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
