name: On Schedule (default branch)

on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onScheduleJob:
    name: Verify code base when pushed
    runs-on: macos-latest
    #    runs-on: ubuntu-20.04-16core # Larger github runner, with KVM acceleration
    steps:
      - name: Run checkout github action
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Generate version name
        id: version-name
        uses: ./config/actions/version-name
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.latest-tag.outputs.current-tag }}

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check

      - name: Run gradle instrumentation tests - en
        uses: ./config/actions/gradle-connected-test
        with:
          architecture: 'arm64-v8a'
          device-profile: 'pixel_xl'
        if: ${{ steps.detect-arch.outputs.arch-in-use }} == 'arm64'
        env:
          ARCH_IN_USE: ${{ steps.detect-arch.outputs.arch-in-use }}

      - name: Run gradle instrumentation tests - en
        uses: ./config/actions/gradle-connected-test
        if: ${{ steps.detect-arch.outputs.arch-in-use }} != 'arm64'
        env:
          ARCH_IN_USE: ${{ steps.detect-arch.outputs.arch-in-use }}
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}

      - name: Run gradle instrumentation tests - cy
        uses: ./config/actions/gradle-connected-test
        with:
          architecture: 'arm64-v8a'
          device-profile: 'pixel_xl'
          locale: cy-GB
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}
        if: ${{ steps.detect-arch.outputs.arch-in-use }} == 'arm64'

      - name: Run gradle instrumentation tests - cy
        uses: ./config/actions/gradle-connected-test
        with:
          locale: cy-GB
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}
        if: ${{ steps.detect-arch.outputs.arch-in-use }} != 'arm64'

      - name: Run sonar analysis
        uses: ./config/actions/sonar-analysis
        with:
          project-version: ${{ steps.version-name.outputs.version-name }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Bundle reports folder
        uses: ./config/actions/bundle-reports
